# 应用配置
spring:
  application:
    name: springboot-shiro
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 20
      test-while-idle: true
      validation-query: select 1
      default-auto-commit: false
      min-idle: 15
      initial-size: 15
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


# 服务器配置
server:
  port: 8888
  compression:
    enabled: true
  servlet:
    session:
      timeout: 7200

#swagger
swagger:
  enable: true
  controller:
    package: cn.wlcloudy.shiro.web.controller

# 日志
logging:
  config: classpath:logback-spring-dev.xml
  path: ./logs/springboot-shiro
  level:
    root: info